version: "3"

services:
  angular:
    container_name: angularcontainer
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - "./:/var/www/html"
    working_dir: /var/www/html
    command: ng serve --host 0.0.0.0 --poll=2000