version: "3"

services:
  frontend:
    container_name: angularfrontend
    extends:
      file: ./frontend/docker-compose.yml
      service: angular
    # build:
    #   context: ./frontend
    #   dockerfile: ./Dockerfile
    # volumes:
    #   - "./:/var/www/html"
    # working_dir: /var/www/html
    # command: cd frontend && ng serve --host 0.0.0.0 --port 80 --poll=2000

  # nginx:
  #   container_name: middlenginx
  #   image: nginx:stable-alpine
  #   expose:
  #     - "80"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
  #   depends_on:
  #     - backend
      
  backend:
    container_name: pocketbasebackend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/pb_data:/pb/pb_data:rw
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
