version: "3"

services:
  frontend:
    container_name: angularfrontend
    extends:
      file: ./frontend/docker-compose.yml
      service: angular
      
  backend:
    container_name: pocketbasebackend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/pb_data:/pb/pb_data:rw
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
